name: Stage

on:
  push:
    #paths:
    #- 'dev'  
  pull_request:
    paths:
    - 'dev/'

jobs:
  run-terraform:
    uses: heyrun/terraform_gitactions/.github/workflows/terraform.yaml@master #to be changed to @master
    with:
      working_dir: 'staging/'
      environ: 'dev'
      if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
      to_apply: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}